
class Constants():
    ids_missing_many_info = [11894976, 11894978, 11978644, 12016952, 12003027,
                             11996976, 11996974, 17531856, 17495503, 17687942,
                             16576547, 16839735, 16576545, 16923729, 17715423,
                             17715424, 17715420, 16923725, 16576528, 16576557,
                             16576555, 16576558, 16576562, 16576566, 16622092,
                             ]
    HOME = "home"
    AWAY = "away"
    DRAW = "draw"
    target_label = {HOME: 0,
                    AWAY: 1,
                    DRAW: 2,
                    }
    TRAIN_MODE = "train"
    PREDICT_MODE = "predict"
    LEFT_JOIN = "left"

class FilePath():
    train_file_path = "data/raw/train.feather"
    predict_file_path = "data/raw/test.feather"
    classification_processed_train_file_path = "data/processed/classification/processed_train_data.feather"
    regression_processed_train_file_path = "data/processed/regression/processed_train_data.feather"
    processed_predict_file_path = "data/processed/processed_predict_data.feather"
    classifier_model_path = "models/saved_models/xgboost_classifier.model"
    regressor_home_model_path = "models/saved_models/xgboost_regressor_home.model"
    regressor_away_model_path = "models/saved_models/xgboost_regressor_away.model"
    classification_evaluation_path = "models/model_evaluations/xgboost_classifier_evaluation.csv"
    regression_home_evaluation_path = "models/model_evaluations/xgboost_regressor_home_evaluation.csv"
    regression_away_evaluation_path = "models/model_evaluations/xgboost_regressor_away_evaluation.csv"
    submission_path = "data/predicted/question_1_submission.csv"
    targets_for_regression_path = "data/raw/targets_for_regression.feather"

class FeatureNames():
    ID = "id"
    MATCH_DATE = "match_date"
    LEAGUE_ID = "league_id"
    IS_CUP = "is_cup"
    TARGET = "target"
    _30_DAY_AGO_MATCH_DATE ="30_day_ago_match_date"
    HOME_TEAM_DAYS_FROM_LAST_MATCH = "home_team_days_from_last_match"
    AWAY_TEAM_DAYS_FROM_LAST_MATCH = "away_team_days_from_last_match"
    HOME_TEAM_HISTORY_MATCH_DATE_1 = "home_team_history_match_date_1"
    AWAY_TEAM_HISTORY_MATCH_DATE_1 = "away_team_history_match_date_1"
    HOME_TEAM_HISTORY_IS_CUP_1 = "home_team_history_is_cup_1"
    AWAY_TEAM_HISTORY_IS_CUP_1 = "away_team_history_is_cup_1"
    HOME_TEAM_HISTORY_GOAL_1 = "home_team_history_goal_1"
    AWAY_TEAM_HISTORY_GOAL_1 = "away_team_history_goal_1"
    HOME_TEAM_HISTORY_RATING_1 = "home_team_history_rating_1"
    AWAY_TEAM_HISTORY_RATING_1 = "away_team_history_rating_1"
    HOME_TEAM_HISTORY_LEAGUE_ID_1 = "home_team_history_league_id_1"
    AWAY_TEAM_HISTORY_LEAGUE_ID_1 = "away_team_history_league_id_1"
    HOME_TEAM_HISTORY_OPPONENT_RATING_1 = "home_team_history_opponent_rating_1"
    AWAY_TEAM_HISTORY_OPPONENT_RATING_1 = "away_team_history_opponent_rating_1"
    HOME_TEAM_HISTORY_OPPONENT_GOAL_1 = "home_team_history_opponent_goal_1"
    AWAY_TEAM_HISTORY_OPPONENT_GOAL_1 = "away_team_history_opponent_goal_1"
    HOME_TEAM_TOTAL_MATCHES_LAST_30_DAYS = "home_team_total_matches_last_30_days"
    AWAY_TEAM_TOTAL_MATCHES_LAST_30_DAYS = "away_team_total_matches_last_30_days"
    HOME_TEAM_MATCHES_PLAY_HOME_LAST_30_DAYS = "home_team_matches_play_home_last_30_days"
    AWAY_TEAM_MATCHES_PLAY_HOME_LAST_30_DAYS = "away_team_matches_play_home_last_30_days"
    HOME_TEAM_MATCHES_CUP_COMP_LAST_10_MATCHES = "home_team_matches_cup_comp_last_10_matches"
    AWAY_TEAM_MATCHES_CUP_COMP_LAST_10_MATCHES = "away_team_matches_cup_comp_last_10_matches"
    HOME_TEAM_MATCHES_CUP_COMP_LAST_30_DAYS = "home_team_matches_cup_comp_last_30_days"
    AWAY_TEAM_MATCHES_CUP_COMP_LAST_30_DAYS = "away_team_matches_cup_comp_last_30_days"
    HOME_TEAM_IS_LAST_MATCH_CUP = "home_team_is_last_match_cup"
    AWAY_TEAM_IS_LAST_MATCH_CUP = "away_team_is_last_match_cup"
    HOME_TEAM_AVG_GOALS_LAST_10_MATCHES = "home_team_avg_goals_last_10_matches"
    AWAY_TEAM_AVG_GOALS_LAST_10_MATCHES = "away_team_avg_goals_last_10_matches"
    HOME_TEAM_AVG_GOALS_LAST_30_DAYS = "home_team_avg_goals_last_30_days"
    AWAY_TEAM_AVG_GOALS_LAST_30_DAYS = "away_team_avg_goals_last_30_days"
    HOME_TEAM_GOALS_LAST_MATCH = "home_team_goals_last_match"
    AWAY_TEAM_GOALS_LAST_MATCH = "away_team_goals_last_match"
    HOME_TEAM_OPPONENT_AVG_GOALS_LAST_10_MATCHES = "home_team_opponent_avg_goals_last_10_matches"
    AWAY_TEAM_OPPONENT_AVG_GOALS_LAST_10_MATCHES = "away_team_opponent_avg_goals_last_10_matches"
    HOME_TEAM_OPPONENT_AVG_GOALS_LAST_30_DAYS = "home_team_opponent_avg_goals_last_30_days"
    AWAY_TEAM_OPPONENT_AVG_GOALS_LAST_30_DAYS = "away_team_opponent_avg_goals_last_30_days"
    HOME_TEAM_OPPONENT_GOALS_LAST_MATCH = "home_team_opponent_goals_last_match"
    AWAY_TEAM_OPPONENT_GOALS_LAST_MATCH = "away_team_opponent_goals_last_match"
    HOME_TEAM_AVG_RATING_LAST_10_MATCHES = "home_team_avg_rating_last_10_matches"
    AWAY_TEAM_AVG_RATING_LAST_10_MATCHES = "away_team_avg_rating_last_10_matches"
    HOME_TEAM_AVG_RATING_LAST_30_DAYS = "home_team_avg_rating_last_30_days"
    AWAY_TEAM_AVG_RATING_LAST_30_DAYS = "away_team_avg_rating_last_30_days"
    HOME_TEAM_RATING_LAST_MATCH = "home_team_rating_last_match"
    AWAY_TEAM_RATING_LAST_MATCH = "away_team_rating_last_match"
    HOME_TEAM_OPPONENT_AVG_RATING_LAST_10_MATCHES = "home_team_opponent_avg_rating_last_10_matches"
    AWAY_TEAM_OPPONENT_AVG_RATING_LAST_10_MATCHES = "away_team_opponent_avg_rating_last_10_matches"
    HOME_TEAM_OPPONENT_AVG_RATING_LAST_30_DAYS = "home_team_opponent_avg_rating_last_30_days"
    AWAY_TEAM_OPPONENT_AVG_RATING_LAST_30_DAYS = "away_team_opponent_avg_rating_last_30_days"
    HOME_TEAM_OPPONENT_RATING_LAST_MATCH = "home_team_opponent_rating_last_match"
    AWAY_TEAM_OPPONENT_RATING_LAST_MATCH = "away_team_opponent_rating_last_match"
    HOME_TEAM_LEAGUES_LAST_10_MATCHES = "home_team_leagues_last_10_matches"
    AWAY_TEAM_LEAGUES_LAST_10_MATCHES = "away_team_leagues_last_10_matches"
    HOME_TEAM_LEAGUES_LAST_30_DAYS = "home_team_leagues_last_30_days"
    AWAY_TEAM_LEAGUES_LAST_30_DAYS = "away_team_leagues_last_30_days"
    HOME_TEAM_SAME_LEAGUE = "home_team_same_league"
    AWAY_TEAM_SAME_LEAGUE = "away_team_same_league"
    FINAL_REDUNDANT_FEATURES = ['home_team_name',
                                'away_team_name',
                                'league_name',
                                'league_id',
                                '30_day_ago_match_date',
                                ]
    DOW_MATCH = "dow_match"
    WEEK_MATCH = "week_match"
    MONTH_MATCH = "month_match"
    YEAR_MATCH = "year_match"
    SCORE = "score"
    HOME_SCORE = "home_score"
    AWAY_SCORE = "away_score"

class Patterns():
    COACH = "coach"
    DATE = "date"
    DATE_INDEX = "date_index"
    HOME_TEAM_DATE_INDEX_ = "home_team_date_index_"
    HOME_TEAM_HISTORY_MATCH_DATE_ = "home_team_history_match_date_"
    AWAY_TEAM_DATE_INDEX_ = "away_team_date_index_"
    AWAY_TEAM_HISTORY_MATCH_DATE_ = "away_team_history_match_date_"
    HOME_TEAM_HISTORY_IS_PLAY_HOME_ = "home_team_history_is_play_home_"
    AWAY_TEAM_HISTORY_IS_PLAY_HOME_ = "away_team_history_is_play_home_"
    HOME_TEAM_HISTORY_IS_CUP_ = "home_team_history_is_cup_"
    AWAY_TEAM_HISTORY_IS_CUP_ = "away_team_history_is_cup_"
    HOME_TEAM_HISTORY_GOALS_ = "home_team_history_goal_"
    AWAY_TEAM_HISTORY_GOALS_ = "away_team_history_goal_"
    HOME_TEAM_HISTORY_OPPONENT_GOAL_ = "home_team_history_opponent_goal_"
    AWAY_TEAM_HISTORY_OPPONENT_GOAL_ = "away_team_history_opponent_goal_"
    HOME_TEAM_HISTORY_RATING_ = "home_team_history_rating_"
    AWAY_TEAM_HISTORY_RATING_ = "away_team_history_rating_"
    HOME_TEAM_HISTORY_OPPONENT_RATING_ = "home_team_history_opponent_rating_"
    AWAY_TEAM_HISTORY_OPPONENT_RATING_ = "away_team_history_opponent_rating_"
    HOME_TEAM_HISTORY_LEAGUE_ID_ = "home_team_history_league_id_"
    AWAY_TEAM_HISTORY_LEAGUE_ID_ = "away_team_history_league_id_"

class DTypes():
    DATETIME_64 = "datetime64[ns]"
    INT32 = "int32"
    INT64 = "int64"
    FLOAT32 = "float32"
    FLOAT64 = "float64"